### ISSUE TITLE
Error: An error occurred setting up the container.

### ISSUE THREAD

**Issue by BillmanH** [microsoft/vscode-azure-iot-tools#49]
Testing the `New IoT Edge Solution`, really, I just want the base code for an edge module. 

Standard and updated versions.  
![image](https://user-images.githubusercontent.com/10108711/175823638-53710e85-64e4-41d6-a3c1-a97b16023e3a.png)

```
[2022-06-26T15:57:11.342Z] Stop (321 ms): Run in container: /bin/sh
[2022-06-26T15:57:11.343Z] Shell server terminated (code: 1, signal: null)
[2022-06-26T15:57:11.343Z] Error response from daemon: Container 13829cc1782be765c99a20645a1952ce10dab6bcdf243996d3cf56fdd5992358 is not running
[2022-06-26T15:57:11.343Z] Start: Run in container: cat /etc/passwd
[2022-06-26T15:57:11.343Z] Stdin closed!
[2022-06-26T15:57:11.344Z] Error: An error occurred setting up the container.
[2022-06-26T15:57:11.344Z]     at NR (c:\Users\william.harding\.vscode\extensions\ms-vscode-remote.remote-containers-0.238.2\dist\spec-node\devContainersSpecCLI.js:239:1572)
[2022-06-26T15:57:11.344Z]     at Jy (c:\Users\william.harding\.vscode\extensions\ms-vscode-remote.remote-containers-0.238.2\dist\spec-node\devContainersSpecCLI.js:239:1510)
[2022-06-26T15:57:11.344Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-26T15:57:11.344Z]     at async zR (c:\Users\william.harding\.vscode\extensions\ms-vscode-remote.remote-containers-0.238.2\dist\spec-node\devContainersSpecCLI.js:245:2006)
[2022-06-26T15:57:11.344Z]     at async nb (c:\Users\william.harding\.vscode\extensions\ms-vscode-remote.remote-containers-0.238.2\dist\spec-node\devContainersSpecCLI.js:245:3110)
[2022-06-26T15:57:11.344Z]     at async JR (c:\Users\william.harding\.vscode\extensions\ms-vscode-remote.remote-containers-0.238.2\dist\spec-node\devContainersSpecCLI.js:245:13046)
[2022-06-26T15:57:11.344Z]     at async KR (c:\Users\william.harding\.vscode\extensions\ms-vscode-remote.remote-containers-0.238.2\dist\spec-node\devContainersSpecCLI.js:245:12802)
[2022-06-26T15:57:11.351Z] Stop (4236 ms): Run: C:\Users\william.harding\AppData\Local\Programs\Microsoft VS Code\Code.exe c:\Users\william.harding\.vscode\extensions\ms-vscode-remote.remote-containers-0.238.2\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\william.harding\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder c:\Users\william.harding\Documents\repos\personalstack\New folder\modules --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\william.harding\Documents\repos\personalstack\New folder\modules --log-level debug --log-format json --config c:\Users\william.harding\Documents\repos\personalstack\New folder\modules\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-06-26T15:57:11.351Z] Exit code 1
[2022-06-26T15:57:11.354Z] Command failed: C:\Users\william.harding\AppData\Local\Programs\Microsoft VS Code\Code.exe c:\Users\william.harding\.vscode\extensions\ms-vscode-remote.remote-containers-0.238.2\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\william.harding\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder c:\Users\william.harding\Documents\repos\personalstack\New folder\modules --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\william.harding\Documents\repos\personalstack\New folder\modules --log-level debug --log-format json --config c:\Users\william.harding\Documents\repos\personalstack\New folder\modules\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-06-26T15:57:11.354Z] Exit code 1
```

I think there might be an issue with docker file sharing local directories. That's just a hunch because the error is pretty ambiguous. 

Any thoughts here as to what I could try?

**Comment by BillmanH** [comment]
that I'm the only one having this issue, closing just for cleanup and maintenance. Opened a new SO post here: https://stackoverflow.com/questions/74296595/running-default-eventhub-function-returns-unexpected-status-code-400
